name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          docker --version
          